apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator
  namespace: mfaizfatah
  labels:
    app: calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator
        imagePullPolicy: Always
        image: mfaizfatah/belajar:alpha
        ports:
        - containerPort: 8080
